### ISSUE TITLE
Unable to open an image

### ISSUE THREAD

**Issue by jsbien** [hsnr-gamera/gamera-4#16]
I've tried to start my work from the scratch and got
`
>> image0 = load_image(r"/home/vmbuster/Gamera/source_image.tiff")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/gamera/core.py", line 119, in load_image
    raise IOError("'%s' could not be loaded." % filename)
OSError: '/home/vmbuster/Gamera/source_image.tiff' could not be loaded.
`
The image in question has been included in my other issue report.

**Comment by jsbien** [comment]
Installing *-dev versions of libraries helped.
