### ISSUE TITLE
Import error with libpng

### ISSUE THREAD

**Issue by OneOverSeven** [hsnr-gamera/gamera-4#9]
Hi,

$ python3 setup.py build
Gamera version: 4.0.pre
Compiling genetic algorithms with parallelization (OpenMP)

skipping wrapper generation for arithmetic plugin (output up-to-date)
skipping wrapper generation for binarization plugin (output up-to-date)
skipping wrapper generation for color plugin (output up-to-date)
skipping wrapper generation for contour plugin (output up-to-date)
skipping wrapper generation for convolution plugin (output up-to-date)
skipping wrapper generation for corelation plugin (output up-to-date)
skipping wrapper generation for deformation plugin (output up-to-date)
skipping wrapper generation for draw plugin (output up-to-date)
skipping wrapper generation for edgedetect plugin (output up-to-date)
skipping wrapper generation for features plugin (output up-to-date)
skipping wrapper generation for fourier_features plugin (output up-to-date)
skipping wrapper generation for geometry plugin (output up-to-date)
skipping wrapper generation for gui_support plugin (output up-to-date)
skipping wrapper generation for image_conversion plugin (output up-to-date)
skipping wrapper generation for image_utilities plugin (output up-to-date)
skipping wrapper generation for listutilities plugin (output up-to-date)
skipping wrapper generation for logical plugin (output up-to-date)
skipping wrapper generation for misc_filters plugin (output up-to-date)
skipping wrapper generation for misc_free_functions plugin (output up-to-date)
skipping wrapper generation for morphology plugin (output up-to-date)
skipping wrapper generation for pagesegmentation plugin (output up-to-date)
skipping wrapper generation for png_support plugin (output up-to-date)
skipping wrapper generation for projections plugin (output up-to-date)
skipping wrapper generation for runlength plugin (output up-to-date)
skipping wrapper generation for segmentation plugin (output up-to-date)
skipping wrapper generation for string_io plugin (output up-to-date)
skipping wrapper generation for structural plugin (output up-to-date)
skipping wrapper generation for thinning plugin (output up-to-date)
skipping wrapper generation for threshold plugin (output up-to-date)
skipping wrapper generation for tiff_support plugin (output up-to-date)
skipping wrapper generation for transformation plugin (output up-to-date)
Traceback (most recent call last):
  File "setup.py", line 228, in <module>
    import wx
  File "/home/mrblue/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/mrblue/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory

$ sudo apt install libpng16-16
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpng16-16 is already the newest version (1.6.34-1ubuntu0.18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo apt-get install g++ python python-dev python-wxgtk2.8 python-wxversion libtiff4-dev libpng12-dev python-docutils python-pygments
[sudo] password for mrblue:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libtiff4-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libtiff5-dev

Package python-wxgtk2.8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-wxgtk2.8' has no installation candidate
E: Package 'libtiff4-dev' has no installation candidate
E: Package 'libpng12-dev' has no installation candidate

$ sudo dpkg -i ./libpng12-dev_1.2.54-1ubuntu1.1_amd64.deb
Selecting previously unselected package libpng12-dev:amd64.
(Reading database ... 56917 files and directories currently installed.)
Preparing to unpack .../libpng12-dev_1.2.54-1ubuntu1.1_amd64.deb ...
Unpacking libpng12-dev:amd64 (1.2.54-1ubuntu1.1) ...
dpkg: dependency problems prevent configuration of libpng12-dev:amd64:
 libpng12-dev:amd64 depends on libpng12-0 (= 1.2.54-1ubuntu1.1); however:
  Package libpng12-0 is not installed.
 libpng12-dev:amd64 depends on zlib1g-dev; however:
  Package zlib1g-dev is not installed.

dpkg: error processing package libpng12-dev:amd64 (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Errors were encountered while processing:
 libpng12-dev:amd64

$ sudo gdebi libpng12-dev_1.2.54-1ubuntu1.1_amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libpng12-0 (= 1.2.54-1ubuntu1.1)

$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux LAPTOP-GST0Q31R 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

It's "Windows Subsystem for Linux" (Yes, Linux on windows 10... hum...)

Same problem with python 2.7 and Gamera-3.4.4, or Python 3.8 and Gamera-4-0.pre in two different virtualenv.

**Comment by OneOverSeven** [comment]
This solves the problem:

$ sudo apt install libpng12-0_1.2.54-1ubuntu1.1_amd64.deb

From this page:
https://askubuntu.com/questions/840257/e-package-libpng12-0-has-no-installation-candidate-ubuntu-16-10-gnome

and this page:

https://packages.ubuntu.com/xenial/amd64/libpng12-0/download 

download link:
http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb

Now it is compiling.

Apologies for the unnecessary issue.
